require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VolunteersJsController do

  # This should return the minimal set of attributes required to create a valid
  # VolunteersJ. As you add validations to VolunteersJ, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VolunteersJsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all volunteers_js as @volunteers_js" do
      volunteers_j = VolunteersJ.create! valid_attributes
      get :index, {}, valid_session
      assigns(:volunteers_js).should eq([volunteers_j])
    end
  end

  describe "GET show" do
    it "assigns the requested volunteers_j as @volunteers_j" do
      volunteers_j = VolunteersJ.create! valid_attributes
      get :show, {:id => volunteers_j.to_param}, valid_session
      assigns(:volunteers_j).should eq(volunteers_j)
    end
  end

  describe "GET new" do
    it "assigns a new volunteers_j as @volunteers_j" do
      get :new, {}, valid_session
      assigns(:volunteers_j).should be_a_new(VolunteersJ)
    end
  end

  describe "GET edit" do
    it "assigns the requested volunteers_j as @volunteers_j" do
      volunteers_j = VolunteersJ.create! valid_attributes
      get :edit, {:id => volunteers_j.to_param}, valid_session
      assigns(:volunteers_j).should eq(volunteers_j)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new VolunteersJ" do
        expect {
          post :create, {:volunteers_j => valid_attributes}, valid_session
        }.to change(VolunteersJ, :count).by(1)
      end

      it "assigns a newly created volunteers_j as @volunteers_j" do
        post :create, {:volunteers_j => valid_attributes}, valid_session
        assigns(:volunteers_j).should be_a(VolunteersJ)
        assigns(:volunteers_j).should be_persisted
      end

      it "redirects to the created volunteers_j" do
        post :create, {:volunteers_j => valid_attributes}, valid_session
        response.should redirect_to(VolunteersJ.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved volunteers_j as @volunteers_j" do
        # Trigger the behavior that occurs when invalid params are submitted
        VolunteersJ.any_instance.stub(:save).and_return(false)
        post :create, {:volunteers_j => {}}, valid_session
        assigns(:volunteers_j).should be_a_new(VolunteersJ)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        VolunteersJ.any_instance.stub(:save).and_return(false)
        post :create, {:volunteers_j => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested volunteers_j" do
        volunteers_j = VolunteersJ.create! valid_attributes
        # Assuming there are no other volunteers_js in the database, this
        # specifies that the VolunteersJ created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        VolunteersJ.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => volunteers_j.to_param, :volunteers_j => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested volunteers_j as @volunteers_j" do
        volunteers_j = VolunteersJ.create! valid_attributes
        put :update, {:id => volunteers_j.to_param, :volunteers_j => valid_attributes}, valid_session
        assigns(:volunteers_j).should eq(volunteers_j)
      end

      it "redirects to the volunteers_j" do
        volunteers_j = VolunteersJ.create! valid_attributes
        put :update, {:id => volunteers_j.to_param, :volunteers_j => valid_attributes}, valid_session
        response.should redirect_to(volunteers_j)
      end
    end

    describe "with invalid params" do
      it "assigns the volunteers_j as @volunteers_j" do
        volunteers_j = VolunteersJ.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VolunteersJ.any_instance.stub(:save).and_return(false)
        put :update, {:id => volunteers_j.to_param, :volunteers_j => {}}, valid_session
        assigns(:volunteers_j).should eq(volunteers_j)
      end

      it "re-renders the 'edit' template" do
        volunteers_j = VolunteersJ.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VolunteersJ.any_instance.stub(:save).and_return(false)
        put :update, {:id => volunteers_j.to_param, :volunteers_j => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested volunteers_j" do
      volunteers_j = VolunteersJ.create! valid_attributes
      expect {
        delete :destroy, {:id => volunteers_j.to_param}, valid_session
      }.to change(VolunteersJ, :count).by(-1)
    end

    it "redirects to the volunteers_js list" do
      volunteers_j = VolunteersJ.create! valid_attributes
      delete :destroy, {:id => volunteers_j.to_param}, valid_session
      response.should redirect_to(volunteers_js_url)
    end
  end

end
