DELIMITER $$

CREATE TRIGGER on_webform_data AFTER INSERT ON WEBFORM_SUBMITTED_DATA FOR EACH ROW
BEGIN
	IF (NEW.CID = 1) THEN
		INSERT INTO user (id, first_name) 
		VALUES (NEW.SID, NEW.DATA) 
		ON DUPLICATE KEY UPDATE first_name = NEW.DATA;
	ELSEIF (NEW.CID=2) THEN
		INSERT INTO user (id, last_name) 
		VALUES (NEW.SID, NEW.DATA) 
		ON DUPLICATE KEY UPDATE last_name = NEW.DATA;
	ELSEIF (NEW.CID=3) THEN
		INSERT INTO user (id, email) 
		VALUES (NEW.SID, NEW.DATA) 
		ON DUPLICATE KEY UPDATE email = NEW.DATA;
	END IF;
END$$
